---

- name: Install minimal system requirements for ansible
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - include_role:
        name: minimalsystem

- name: Install common components
  hosts: all
  gather_facts: true
  become: yes
  tasks:
    - include_role:
        name: common

- name: Install NTP
  hosts: all
  gather_facts: true
  become: yes
  tasks:
    - include_role:
        name: ntpserver

...
